
---

# E) (Nice to have) Automated linting in GitHub (acts like pre-commit)
This runs **Black** and **Ruff** on every push in the cloud (no setup on your laptop yet).

1) **Add file → Create new file**  
2) **Name:** `.github/workflows/lint.yml`  
3) Paste:
```yaml
name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install black ruff
      - run: black --check .
      - run: ruff check .
