name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install black ruff

      - name: Black (only if Python files exist)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: black --check .

      - name: Ruff (only if Python files exist)
        if: ${{ hashFiles('**/*.py') != '' }}
        run: ruff check .
